FROM zhujun/spark-local-python-template

# ENV SPARK_MASTER_NAME spark-master
# ENV SPARK_MASTER_PORT 7077
ENV SPARK_APPLICATION_PYTHON_LOCATION /app/spark_script1.py
# ENV SPARK_APPLICATION_ARGS

CMD ["/bin/bash"]